### ISSUE TITLE
When I tried to use it I have error

### ISSUE THREAD

**Issue by voltento** [nmathewson/mmdb-convert#5]
Traceback (most recent call last):
  File "./mmdb-convert.py", line 441, in <module>
    metadata, the_tree, _ = parse_mm_file(content)
  File "./mmdb-convert.py", line 327, in parse_mm_file
    tree = parse_search_tree(s[:tree_size], mm['record_size'].int_val())
  File "./mmdb-convert.py", line 123, in parse_search_tree
    left, right = to_leftright(s[p:p+record_bytes])
  File "./mmdb-convert.py", line 80, in to_int28
    a, b = unpack("!LL", s + b'\x00')
NameError: global name 'unpack' is not defined

Can you add a requirements file? please?

**Comment by mnicky** [comment]
see fix in https://github.com/nmathewson/mmdb-convert/pull/2

**Comment by nmathewson** [comment]
Merged the fix.  But, um, what are you using this code for?  I didn't think anybody was using this.

**Comment by mnicky** [comment]
I was just searching for a way to build the legacy geoip `.dat` files (from csv or mmdb files) and found your project besides others. However, I'm affected by #3 as well :)
